export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERRO";

export const COMENZAR_DESCARGA_PRODUCTOS = "COMENZAR_DESCARGA_PRODUCTOS";
export const DESCARGA_PRODUCTOS_EXITO = "DESCARGA_PRODUCTOS_EXITO";
export const DESCARGA_PRODUCTOS_ERROR = "DESCARGA_PRODUCTOS_ERROR";

export const COMENZAR_ELIMINACION_PRODUCTO = "COMENZAR_ELIMINACION_PRODUCTO";
export const ELIMINACION_PRODUCTO_EXITO = "ELIMINACION_PRODUCTO_EXITO";
export const ELIMINACION_PRODUCTO_ERROR = "ELIMINACION_PRODUCTO_ERROR";